### ISSUE TITLE
Race condition when calling intercom and using secure mode

### ISSUE THREAD

**Issue by rantav** [versolearning/meteor-intercom#12]
I found out that in some cases when using secure mode with this package there's a race condition that causes Intercom's load failure. 

Repro: 

1. Create a meteor app and add mateor-intercom. Add the app id and secret key to the settings file
2. Deploy your app to remote servers (this never happened to me on localhost, only remote servers - aka a race condition)
3. Login to your app => Intercom works as expected
4. Reload the page (do not log out) => Intercom fails with 403 to the /ping HTTP POST request

If you look at the network inspector you see that the call to /ping lacks `user_data.user_hash` which is required for secure communication. 
Again, as noted, this is a race condition, sometimes happens (happens to me a lot) but sometimes it doesn't. It happens only after logging in and then refreshing the page (while the user is still logged in). The problem is that the `user.intercomHash` value doesn't exist yet on the user object.

Workaround: 
I found a workaround using the function `IntercomSettings.userInfo`:
```
IntercomSettings.userInfo = function (user, info) {
  if (!user.intercomHash) {
    return false; // the hash isn't loaded to the users collection yet. come back later. 
  }
  //...
}
```

While implementing this workaround is fine by me, I think most users would appreciate a proper fix at the package level, just before invoking the function `IntercomSettings.userInfo`

HTH

**Comment by tmeasday** [comment]
If I remember properly, the problem is that some apps don't have secure mode turned on, so it doesn't make sense to have an `intercomHash` for those users. Not sure of a better solution really...

**Comment by rantav** [comment]
Hi @tmeasday would you like me to at least add a tip to the documentation about my workaround? That might save some ppl time. 
Happy to do that.

**Comment by em0ney** [comment]
Thanks @rantav - the workaround worked a treat for me

This should definitely live in the README imo
