### ISSUE TITLE
How can I update user properties without the user starting a session?

### ISSUE THREAD

**Issue by jamiewilson** [versolearning/meteor-intercom#17]
I'm passing in some new custom properties and the key shows up in Intercom but but the  values don't update until that user comes back to the app. Is there a way to update those values regardless of the user being logged in?

I'm sure the answer is here: http://docs.intercom.io/install-on-your-web-product/intercom-javascript-api, I'm just not sure how to incorporate this with the package. thanks for the help!

**Comment by shelkie** [comment]
You can send updates to Intercom from the server. See the [intercom-node docs](https://github.com/intercom/intercom-node) and the example in the package notes. You'd want to do something like this:

`IntercomClient.users.create({
    user_id: <meteor-user-id>,
    email: 'name@domain.com',
    name: 'Jane Doe',
    custom_attributes: {
        foo: 'bar'
    }
})
`
The IntercomClients.users.create method will update the user if it exists, or create if it doesn't.

Hope this helps.

**Comment by zol** [comment]
Thanks for chiming in here @shelkie !

**Comment by dburles** [comment]
Hey @jamiewilson did @shelkie's advice help you here?

**Comment by jamiewilson** [comment]
Yes, thank you!
