### ISSUE TITLE
Change widget / activator id? 

### ISSUE THREAD

**Issue by nadeemja** [versolearning/meteor-intercom#18]
How do I do it with this package?

**Comment by dburles** [comment]
@nadeemja can you provide some more detail?

**Comment by nadeemja** [comment]
Hello! 

A while since I worked on this, but I think I figured it out. If I recall correctly, you just specify this where you specify all the other settings :)

**Comment by nadeemja** [comment]
Okey, so I forgot how to do this, and just spent an hour figuring it out again. Putting it here for next time and for others:

    IntercomSettings.userInfo = function ( user, info ) {

	    ...

	    info.widget = {
		    "activator": "#YourElement"
	    };

    };

**Comment by morgs32** [comment]
Any chance you figured out how to change the activator dynamically? Such as - use the default one when it's suitable, but when there's a lot of content behind it in the bottom right hand part of the screen, switch to a custom activator button

**Comment by shelkie** [comment]
Should be able to hide the default launcher with CSS
`#intercom-launcher{display:none;}`
and then trigger its click event when your custom button is clicked.
`$('.customButton').click(function(){
$('#intercom-launcher').trigger('click');
});`
