### ISSUE TITLE
Intercom client features

### ISSUE THREAD

**Issue by kennyhyun** [versolearning/meteor-intercom#30]
Thanks for the awesome package.
after your loader function executed, we can use `Intercom()` function.
we need to use it to add an event from the client side like `Intercom('trackEvent', 'custom-event')`.
and also `Intercom('update')` to interact with the users.
Do you have a plan to support those method in your package? or do we need to keep using `Intercom` directly.
I think it will be better if README.md have a mention for those methods.

https://docs.intercom.io/install-on-your-product-or-site/other-ways-to-get-started/integrate-intercom-in-a-single-page-app

**Comment by dburles** [comment]
Hey @kennyhyun using Intercom directly makes sense to me

**Comment by kennyhyun** [comment]
@dburles Thanks for comment.

okay.

but I am still not sure about it.
have you thought about updating in every changes of routing?

the article above says.. (sorry for the missing quatation)

> But if a user has just caused a “page" change, you would call: window.Intercom('update');

on every routing, it needs to be updated. (other multi pages apps are not needed)
it is also okay to omitted since it is actually a ping.
if I need throttling, like for 10 seconds, it would be nice to be done in one place.

I am good for as it is. I just want to know how others think.

**Comment by dburles** [comment]
The purpose of this package is to handle the boilerplate in getting Intercom loaded and setup, I don't know whether it would be best for it to try to handle too much.

**Comment by dburles** [comment]
Though if you do end up coming up with something that you think makes sense to be included, I'll definitely take a look at it

**Comment by kennyhyun** [comment]
I've been thinking about that, but I could not find anything make sense. if I happen to find something, come again. Thanks.
