### ISSUE TITLE
How to specify app id?

### ISSUE THREAD

**Issue by geritol** [versolearning/meteor-intercom#7]
Hi!
I am trying to specify Meteor.settings.public.intercom.id
but i get:  TypeError: Cannot read property 'intercom' of undefined

could you please paste how to specify intercom.id?

Thanks a lot!

**Comment by payner35** [comment]
you need a config/settings.json file in your root folder..

```
{
    "public":{
        "intercom":{
            "id": "[your app ID]"
        }
    },
    "intercom":{
        "secret": "[your secret ID]"
    }
}

```
The package then pulls form this...

**Comment by nadeemja** [comment]
This should be in the docs. :)
